

CREATE TABLE commune (
    id_commune INT AUTO_INCREMENT NOT NULL,
    nom_commune VARCHAR(100) NOT NULL,
    code_postal VARCHAR(5) NOT NULL,
    type_commune VARCHAR(50) NOT NULL DEFAULT 'urbain',
    date_creation DATE NOT NULL,
    PRIMARY KEY (id_commune),
    UNIQUE (nom_commune)
);

CREATE TABLE citoyen (
    id_citoyen INT AUTO_INCREMENT NOT NULL,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telephone VARCHAR(20) NOT NULL,
    date_de_naissance DATE NOT NULL,
    lieu_de_naissance VARCHAR(200) NOT NULL,
    nom_du_pere VARCHAR(100) NOT NULL,
    prenom_du_pere VARCHAR(100) NOT NULL,
    nom_mere VARCHAR(100) NOT NULL,
    prenom_mere VARCHAR(100) NOT NULL,
    id_commune INT NOT NULL,
    PRIMARY KEY (id_citoyen)
);

CREATE TABLE EXTRAIT_DE_NAISSANCE (
    ID_EXTRAIT INT AUTO_INCREMENT NOT NULL,
    NUMEROS_ACTE VARCHAR(50) NOT NULL,
    DATE_ETABLISSEMENT DATE NOT NULL,
    ID_CITOYEN INT NOT NULL,
    ID_COMMUNE INT NOT NULL,
    OFFICIER_ETAT_CIVIL VARCHAR(200),
    PRIMARY KEY (ID_EXTRAIT),
    UNIQUE (NUMEROS_ACTE)
);

CREATE TABLE ACTE_DE_MARIAGE (
    ID_ACTE INT AUTO_INCREMENT NOT NULL,
    NUMEROS_ACTE VARCHAR(50) NOT NULL,
    DATE_DE_MARIAGE DATE NOT NULL,
    ID_CONJOINT INT NOT NULL,
    ID_COMMUNE INT NOT NULL,
    TEMOINS VARCHAR(1000),
    PRIMARY KEY (ID_ACTE),
    UNIQUE (NUMEROS_ACTE)
);

CREATE TABLE TYPE_COMMUNE (
    id INT AUTO_INCREMENT NOT NULL,
    LIBELLE VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (LIBELLE)
);

CREATE TABLE COMMUNES (
    id INT AUTO_INCREMENT NOT NULL,
    NOM_COMMUNE VARCHAR(100) NOT NULL,
    TYPE_ID INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ACTE_DECES (
    ID_DECES INT AUTO_INCREMENT NOT NULL,
    NUMEROS_ACTE VARCHAR(50) NOT NULL,
    DATE_DECES DATE NOT NULL,
    ID_DEFUNT INT NOT NULL,
    ID_COMMUNE INT NOT NULL,
    CAUSE_DECES VARCHAR(255) NOT NULL,
    DECLARANT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_DECES),
    UNIQUE (NUMEROS_ACTE)
);

CREATE TABLE TIMBRES (
    id INT AUTO_INCREMENT NOT NULL,
    CODE_TIMBRE VARCHAR(20) NOT NULL,
    DATE_CREATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUT VARCHAR(10) NOT NULL DEFAULT 'VALIDE',
    ID_CITOYEN INT NOT NULL,
    ID_EXTRAIT_DE_NAISSANCE INT,
    ID_ACTE_DE_MARIAGE INT,
    ID_ACTE_DECES INT,
    PRIMARY KEY (id),
    UNIQUE (CODE_TIMBRE)
);

CREATE TABLE STATUS (
    id INT AUTO_INCREMENT NOT NULL,
    LIBELLE VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (LIBELLE)
);

CREATE TABLE DOCUMENTS (
    id INT AUTO_INCREMENT NOT NULL,
    STATUT_ID INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ADMIN (
    id INT AUTO_INCREMENT NOT NULL,
    PSEUDO_ADMIN VARCHAR(50) NOT NULL,
    MOT_DE_PASS VARCHAR(255) NOT NULL,
    EMAIL_ADMIN VARCHAR(100) NOT NULL,
    DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    TENTATIVE_CONNEXION INT NOT NULL DEFAULT 0,
    BLOQUE_JUSQUA DATETIME,
    PRIMARY KEY (id),
    UNIQUE (PSEUDO_ADMIN),
    UNIQUE (EMAIL_ADMIN)
);

CREATE TABLE AUDIT_ADMIN (
    ID_AUDIT INT AUTO_INCREMENT NOT NULL,
    ID_ADMIN INT NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    DETAIL TEXT NOT NULL,
    ADRESS_IP VARCHAR(45) NOT NULL,
    DATE_ET_HEURE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_AUDIT)
);

-- Clés étrangères
ALTER TABLE citoyen ADD FOREIGN KEY (id_commune) REFERENCES commune(id_commune);
ALTER TABLE EXTRAIT_DE_NAISSANCE ADD FOREIGN KEY (ID_CITOYEN) REFERENCES citoyen(id_citoyen);
ALTER TABLE EXTRAIT_DE_NAISSANCE ADD FOREIGN KEY (ID_COMMUNE) REFERENCES commune(id_commune);
ALTER TABLE ACTE_DE_MARIAGE ADD FOREIGN KEY (ID_CONJOINT) REFERENCES citoyen(id_citoyen);
ALTER TABLE ACTE_DE_MARIAGE ADD FOREIGN KEY (ID_COMMUNE) REFERENCES commune(id_commune);
ALTER TABLE COMMUNES ADD FOREIGN KEY (TYPE_ID) REFERENCES TYPE_COMMUNE(id);
ALTER TABLE ACTE_DECES ADD FOREIGN KEY (ID_DEFUNT) REFERENCES citoyen(id_citoyen);
ALTER TABLE ACTE_DECES ADD FOREIGN KEY (ID_COMMUNE) REFERENCES commune(id_commune);
ALTER TABLE TIMBRES ADD FOREIGN KEY (ID_CITOYEN) REFERENCES citoyen(id_citoyen);
ALTER TABLE TIMBRES ADD FOREIGN KEY (ID_EXTRAIT_DE_NAISSANCE) REFERENCES EXTRAIT_DE_NAISSANCE(ID_EXTRAIT);
ALTER TABLE TIMBRES ADD FOREIGN KEY (ID_ACTE_DE_MARIAGE) REFERENCES ACTE_DE_MARIAGE(ID_ACTE);
ALTER TABLE TIMBRES ADD FOREIGN KEY (ID_ACTE_DECES) REFERENCES ACTE_DECES(ID_DECES);
ALTER TABLE DOCUMENTS ADD FOREIGN KEY (STATUT_ID) REFERENCES STATUS(id);
ALTER TABLE AUDIT_ADMIN ADD FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(id);