CREATE TABLE [commune] (
	[id_commune] int IDENTITY(1,1) NOT NULL UNIQUE,
	[nom_commune] nvarchar(100) NOT NULL UNIQUE,
	[code_postal] nvarchar(5) NOT NULL,
	[type_commune] nvarchar(50) NOT NULL DEFAULT 'urbain',
	[date_creation] date NOT NULL,
	PRIMARY KEY ([id_commune])
);

CREATE TABLE [citoyen] (
	[id_citoyen] int IDENTITY(1,1) NOT NULL UNIQUE,
	[nom] nvarchar(100) NOT NULL,
	[prenom] nvarchar(100) NOT NULL,
	[email] nvarchar(255) NOT NULL,
	[telephone] nvarchar(20) NOT NULL,
	[dae_de_naissance] date NOT NULL,
	[lieu_de_naissance] nvarchar(200) NOT NULL,
	[nom_du_pere] nvarchar(100) NOT NULL,
	[prenom_du_pere] nvarchar(100) NOT NULL,
	[nom_mere] nvarchar(100) NOT NULL,
	[prenom_mere] nvarchar(100) NOT NULL,
	[id_commune] int NOT NULL,
	PRIMARY KEY ([id_citoyen])
);

CREATE TABLE [EXTRAIT_DE_NAISSANCE] (
	[ID_EXTRAIT] int IDENTITY(1,1) NOT NULL UNIQUE,
	[NUMEROS_ACTE] nvarchar(50) NOT NULL UNIQUE,
	[DATE_ETABLISSEMENT] date NOT NULL,
	[ID_CITOYEN] int NOT NULL,
	[ID_COMMUNE] int NOT NULL,
	[OFFICIER_ETAT_CIVIL] nvarchar(200),
	PRIMARY KEY ([ID_EXTRAIT])
);

CREATE TABLE [ACTE_DE_MARIAGE] (
	[ID_ACTE] int IDENTITY(1,1) NOT NULL UNIQUE,
	[NUMEROS_ACTE] nvarchar(50) NOT NULL UNIQUE,
	[DATE_DE_MARIAGE] date NOT NULL,
	[ID_CONJOINT] int NOT NULL,
	[ID_COMMUNE] int NOT NULL,
	[TEMOINS] nvarchar(1000),
	PRIMARY KEY ([ID_ACTE])
);

CREATE TABLE [TYPE_COMMUNE] (
	[id] int IDENTITY(1,1) NOT NULL UNIQUE,
	[LIBELLE] nvarchar(20) NOT NULL UNIQUE,
	PRIMARY KEY ([id])
);

CREATE TABLE [COMMUNES] (
	[id] int IDENTITY(1,1) NOT NULL UNIQUE,
	[NOM_COMMUNE] nvarchar(100) NOT NULL,
	[TYPE_ID] int NOT NULL,
	PRIMARY KEY ([id])
);

CREATE TABLE [ACTE_DECES] (
	[ID_DECES] int IDENTITY(1,1) NOT NULL,
	[NUMEROS_ACTE] nvarchar(50) NOT NULL UNIQUE,
	[DATE_DECES] date NOT NULL,
	[ID_DEFUNT] int NOT NULL,
	[ID_COMMUNE] int NOT NULL,
	[CAUSE_DECES] nvarchar(255) NOT NULL,
	[DECLARANT] nvarchar(255) NOT NULL,
	PRIMARY KEY ([ID_DECES])
);

CREATE TABLE [TIMBRES] (
	[id] int IDENTITY(1,1) NOT NULL UNIQUE,
	[CODE_TIMBRE] nvarchar(20) NOT NULL UNIQUE,
	[DATE_CREATION] datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[STATUT] nvarchar(10) NOT NULL DEFAULT 'VALIDE',
	[ID_CITOYEN] int NOT NULL,
	[ID_EXTRAIT_DE_NAISSANCE] int,
	[ID_ACTE_DE_MARIAGE] int,
	[ID_ACTE_DECES] int,
	PRIMARY KEY ([id])
);

CREATE TABLE [STATUS] (
	[id] int IDENTITY(1,1) NOT NULL UNIQUE,
	[LIBELLE] nvarchar(20) NOT NULL UNIQUE,
	PRIMARY KEY ([id])
);

CREATE TABLE [DOCUMENTS] (
	[id] int IDENTITY(1,1) NOT NULL UNIQUE,
	[STATUT_ID] int NOT NULL,
	PRIMARY KEY ([id])
);

CREATE TABLE [ADMIN] (
	[id] int IDENTITY(1,1) NOT NULL UNIQUE,
	[PSEUDO_ADMIN] nvarchar(50) NOT NULL UNIQUE,
	[MOT_DE_PASS] nvarchar(255) NOT NULL,
	[EMAIL_ADMIN] nvarchar(100) NOT NULL UNIQUE,
	[DATE_CREATION] datetime DEFAULT CURRENT_TIMESTAMP,
	[TENTATIVE_CONNEXION] int NOT NULL DEFAULT 0,
	[BLOQUE_JUSQUA] datetime,
	PRIMARY KEY ([id])
);

CREATE TABLE [AUDIT_ADMIN] (
	[ID_AUDIT] int IDENTITY(1,1) NOT NULL UNIQUE,
	[ID_ADMIN] int NOT NULL,
	[ACTION] nvarchar(50) NOT NULL,
	[DETAIL] nvarchar(max) NOT NULL,
	[ADRESS_IP] nvarchar(45) NOT NULL,
	[DATE_ET_HEURE] datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ([ID_AUDIT])
);


ALTER TABLE [citoyen] ADD CONSTRAINT [citoyen_fk11] FOREIGN KEY ([id_commune]) REFERENCES [commune]([id_commune]);
ALTER TABLE [EXTRAIT_DE_NAISSANCE] ADD CONSTRAINT [EXTRAIT_DE_NAISSANCE_fk3] FOREIGN KEY ([ID_CITOYEN]) REFERENCES [citoyen]([id_citoyen]);

ALTER TABLE [EXTRAIT_DE_NAISSANCE] ADD CONSTRAINT [EXTRAIT_DE_NAISSANCE_fk4] FOREIGN KEY ([ID_COMMUNE]) REFERENCES [commune]([id_commune]);
ALTER TABLE [ACTE_DE_MARIAGE] ADD CONSTRAINT [ACTE_DE_MARIAGE_fk3] FOREIGN KEY ([ID_CONJOINT]) REFERENCES [citoyen]([id_citoyen]);

ALTER TABLE [ACTE_DE_MARIAGE] ADD CONSTRAINT [ACTE_DE_MARIAGE_fk4] FOREIGN KEY ([ID_COMMUNE]) REFERENCES [commune]([id_commune]);

ALTER TABLE [COMMUNES] ADD CONSTRAINT [COMMUNES_fk2] FOREIGN KEY ([TYPE_ID]) REFERENCES [TYPE_COMMUNE]([id]);
ALTER TABLE [ACTE_DECES] ADD CONSTRAINT [ACTE_DECES_fk3] FOREIGN KEY ([ID_DEFUNT]) REFERENCES [citoyen]([id_citoyen]);

ALTER TABLE [ACTE_DECES] ADD CONSTRAINT [ACTE_DECES_fk4] FOREIGN KEY ([ID_COMMUNE]) REFERENCES [commune]([id_commune]);
ALTER TABLE [TIMBRES] ADD CONSTRAINT [TIMBRES_fk4] FOREIGN KEY ([ID_CITOYEN]) REFERENCES [citoyen]([id_citoyen]);

ALTER TABLE [TIMBRES] ADD CONSTRAINT [TIMBRES_fk5] FOREIGN KEY ([ID_EXTRAIT_DE_NAISSANCE]) REFERENCES [EXTRAIT_DE_NAISSANCE]([ID_EXTRAIT]);

ALTER TABLE [TIMBRES] ADD CONSTRAINT [TIMBRES_fk6] FOREIGN KEY ([ID_ACTE_DE_MARIAGE]) REFERENCES [ACTE_DE_MARIAGE]([ID_ACTE]);

ALTER TABLE [TIMBRES] ADD CONSTRAINT [TIMBRES_fk7] FOREIGN KEY ([ID_ACTE_DECES]) REFERENCES [ACTE_DECES]([ID_DECES]);

ALTER TABLE [DOCUMENTS] ADD CONSTRAINT [DOCUMENTS_fk1] FOREIGN KEY ([STATUT_ID]) REFERENCES [STATUS]([id]);

ALTER TABLE [AUDIT_ADMIN] ADD CONSTRAINT [AUDIT_ADMIN_fk1] FOREIGN KEY ([ID_ADMIN]) REFERENCES [ADMIN]([id]);